// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnGw2DHnFYC7jKSmCI_LuExQSPGKlxQng',
    appId: '1:672341818129:android:cd1f4a49edeb036bcceab0',
    messagingSenderId: '672341818129',
    projectId: 'territory-application',
    databaseURL: 'https://territory-application-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'territory-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLuoPIqiVgb0-_qGw9pW1iXRxyyhtMkQc',
    appId: '1:672341818129:ios:c381e495097818eacceab0',
    messagingSenderId: '672341818129',
    projectId: 'territory-application',
    databaseURL: 'https://territory-application-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'territory-application.appspot.com',
    iosClientId: '672341818129-8v0076tfl1qdg0nf4so4mc9q45qc0bie.apps.googleusercontent.com',
    iosBundleId: 'com.example.jwTerritori',
  );
}
